language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env:
  - REPO=elasticsearch NAME=elasticsearch TAG=7.6.0
  - REPO=kibana NAME=kibana TAG=7.6.0
  - REPO=beats NAME=auditbeat TAG=7.6.0
  - REPO=beats NAME=filebeat TAG=7.6.0
  - REPO=beats NAME=heartbeat TAG=7.6.0
  - REPO=beats NAME=journalbeat TAG=7.6.0
  - REPO=beats NAME=metricbeat TAG=7.6.0
  - REPO=beats NAME=packetbeat TAG=7.6.0
  - REPO=logstash NAME=logstash TAG=7.6.0
  - REPO=apm NAME=apm-server TAG=7.6.0
  - REPO=app-search NAME=app-search TAG=7.6.0

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull docker.elastic.co/$REPO/$NAME:$TAG
  - docker tag docker.elastic.co/$REPO/$NAME:$TAG alvisisme/$NAME:$TAG
  - docker push alvisisme/$NAME:$TAG
